version: '3.8'
services:
  shuffullsql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password!
    ports:
      - "1433:1433"
    container_name: shuffullsql
    restart: unless-stopped